"""Refactor Vouchers to Digital Code System

Revision ID: 7a5db2f9da1f
Revises: bf1832e7e1be
Create Date: 2026-03-12 15:22:34.094413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a5db2f9da1f'
down_revision: Union[str, None] = 'bf1832e7e1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift_cards')
    op.drop_constraint(op.f('voucher_redemptions_guest_id_fkey'), 'voucher_redemptions', type_='foreignkey')
    op.drop_column('voucher_redemptions', 'guest_id')
    op.add_column('vouchers', sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('vouchers', sa.Column('amount_remaining', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('vouchers', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('vouchers', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('vouchers', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('vouchers', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vouchers', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('vouchers', sa.Column('notes', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'vouchers', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vouchers', 'max_uses')
    op.drop_column('vouchers', 'voucher_type')
    op.drop_column('vouchers', 'max_discount')
    op.drop_column('vouchers', 'value')
    op.drop_column('vouchers', 'valid_until')
    op.drop_column('vouchers', 'valid_from')
    op.drop_column('vouchers', 'min_order_value')
    op.drop_column('vouchers', 'applicable_items_json')
    op.drop_column('vouchers', 'uses_count')
    op.drop_column('vouchers', 'is_active')
    op.drop_column('vouchers', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('uses_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('applicable_items_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('min_order_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('max_discount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('voucher_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('vouchers', sa.Column('max_uses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vouchers', type_='foreignkey')
    op.drop_column('vouchers', 'notes')
    op.drop_column('vouchers', 'created_by_user_id')
    op.drop_column('vouchers', 'expiry_date')
    op.drop_column('vouchers', 'status')
    op.drop_column('vouchers', 'customer_email')
    op.drop_column('vouchers', 'customer_name')
    op.drop_column('vouchers', 'amount_remaining')
    op.drop_column('vouchers', 'amount_total')
    op.add_column('voucher_redemptions', sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('voucher_redemptions_guest_id_fkey'), 'voucher_redemptions', 'guest_profiles', ['guest_id'], ['id'], ondelete='SET NULL')
    op.create_table('gift_cards',
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('initial_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('purchaser_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('purchaser_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gift_cards_pkey')),
    sa.UniqueConstraint('code', name=op.f('gift_cards_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
