"""Add HMS models

Revision ID: 95069ca497e7
Revises: b1c2d3e4f5a6
Create Date: 2026-03-15 23:07:17.563836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95069ca497e7'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hms_properties',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hms_room_types',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hms_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hms_reservations',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['hms_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hms_reservations_check_in'), 'hms_reservations', ['check_in'], unique=False)
    op.create_index(op.f('ix_hms_reservations_check_out'), 'hms_reservations', ['check_out'], unique=False)
    op.create_table('hms_rooms',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['hms_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['hms_room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('guest_profiles_email_key'), 'guest_profiles', type_='unique')
    op.drop_index(op.f('ix_guest_profiles_email'), table_name='guest_profiles')
    op.create_index(op.f('ix_guest_profiles_email'), 'guest_profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_profiles_email'), table_name='guest_profiles')
    op.create_index(op.f('ix_guest_profiles_email'), 'guest_profiles', ['email'], unique=False)
    op.create_unique_constraint(op.f('guest_profiles_email_key'), 'guest_profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_table('hms_rooms')
    op.drop_index(op.f('ix_hms_reservations_check_out'), table_name='hms_reservations')
    op.drop_index(op.f('ix_hms_reservations_check_in'), table_name='hms_reservations')
    op.drop_table('hms_reservations')
    op.drop_table('hms_room_types')
    op.drop_table('hms_properties')
    # ### end Alembic commands ###
