"""phase1_payment_receipts_upsell_supplier

Revision ID: c7b21a91ffb3
Revises: 2bf2efd05bb7
Create Date: 2026-03-02 01:01:56.689732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b21a91ffb3'
down_revision: Union[str, None] = '2bf2efd05bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kds_station_configs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('category_ids_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_sound', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_purchase_rules',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('reorder_quantity', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_catalog_items',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('supplier_sku', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('min_order_qty', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upsell_rules',
    sa.Column('trigger_item_id', sa.Integer(), nullable=False),
    sa.Column('suggested_item_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_shown', sa.Integer(), nullable=False),
    sa.Column('times_accepted', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['suggested_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_shifts',
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bills', sa.Column('tip_suggestions_json', sa.JSON(), nullable=True))
    op.add_column('bills', sa.Column('receipt_email', sa.String(length=255), nullable=True))
    op.add_column('bills', sa.Column('receipt_phone', sa.String(length=50), nullable=True))
    op.add_column('bills', sa.Column('receipt_token', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'bills', ['receipt_token'])
    op.add_column('order_items', sa.Column('station', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('course_number', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payments', sa.Column('gateway_reference', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('card_last_four', sa.String(length=4), nullable=True))
    op.add_column('payments', sa.Column('card_brand', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('wallet_type', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('refund_of_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'payments', ['refund_of_id'], ['id'], ondelete='SET NULL')
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('actual_delivery_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('delivery_status', sa.String(length=20), nullable=False))
    op.add_column('purchase_orders', sa.Column('received_items_json', sa.JSON(), nullable=True))
    op.add_column('purchase_orders', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('table_orders', sa.Column('guest_name', sa.String(length=255), nullable=True))
    op.add_column('vendors', sa.Column('delivery_days_json', sa.JSON(), nullable=True))
    op.add_column('vendors', sa.Column('minimum_order_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('vendors', sa.Column('catalog_url', sa.String(length=500), nullable=True))
    op.add_column('vendors', sa.Column('payment_terms', sa.String(length=100), nullable=True))
    op.add_column('vendors', sa.Column('lead_time_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'lead_time_days')
    op.drop_column('vendors', 'payment_terms')
    op.drop_column('vendors', 'catalog_url')
    op.drop_column('vendors', 'minimum_order_value')
    op.drop_column('vendors', 'delivery_days_json')
    op.drop_column('table_orders', 'guest_name')
    op.drop_column('purchase_orders', 'notes')
    op.drop_column('purchase_orders', 'received_items_json')
    op.drop_column('purchase_orders', 'delivery_status')
    op.drop_column('purchase_orders', 'actual_delivery_date')
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'refund_of_id')
    op.drop_column('payments', 'wallet_type')
    op.drop_column('payments', 'card_brand')
    op.drop_column('payments', 'card_last_four')
    op.drop_column('payments', 'gateway_reference')
    op.drop_column('payments', 'processing_fee')
    op.drop_column('order_items', 'course_number')
    op.drop_column('order_items', 'station')
    op.drop_constraint(None, 'bills', type_='unique')
    op.drop_column('bills', 'receipt_token')
    op.drop_column('bills', 'receipt_phone')
    op.drop_column('bills', 'receipt_email')
    op.drop_column('bills', 'tip_suggestions_json')
    op.drop_table('cash_shifts')
    op.drop_table('upsell_rules')
    op.drop_table('supplier_catalog_items')
    op.drop_table('auto_purchase_rules')
    op.drop_table('kds_station_configs')
    # ### end Alembic commands ###
