"""increase table_number length

Revision ID: e277dec60b9a
Revises: 9d372db4a5f1
Create Date: 2026-03-11 17:18:59.409878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e277dec60b9a'
down_revision: Union[str, None] = '9d372db4a5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_owner'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_audit_events_actor_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_source_module'), table_name='audit_events')
    op.alter_column('auto_purchase_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_auto_purchase_rules_restaurant_id'), table_name='auto_purchase_rules')
    op.alter_column('bills', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_bills_restaurant_id'), table_name='bills')
    op.alter_column('cash_shifts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_cash_shifts_restaurant_id'), table_name='cash_shifts')
    op.alter_column('floor_sections', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_floor_sections_restaurant_id'), table_name='floor_sections')
    op.alter_column('guest_profiles', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_guest_profiles_restaurant_id'), table_name='guest_profiles')
    op.alter_column('inventory_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_inventory_items_restaurant_id'), table_name='inventory_items')
    op.alter_column('inventory_movements', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_inventory_movements_restaurant_id'), table_name='inventory_movements')
    op.alter_column('kds_station_configs', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_kds_station_configs_restaurant_id'), table_name='kds_station_configs')
    op.alter_column('loyalty_accounts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_loyalty_accounts_restaurant_id'), table_name='loyalty_accounts')
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_menu_categories_restaurant_id'), table_name='menu_categories')
    op.alter_column('menu_combos', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_menu_combos_restaurant_id'), table_name='menu_combos')
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.alter_column('menu_modifiers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_menu_modifiers_restaurant_id'), table_name='menu_modifiers')
    op.alter_column('order_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_order_items_restaurant_id'), table_name='order_items')
    op.alter_column('orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.alter_column('payments', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_payments_restaurant_id'), table_name='payments')
    op.alter_column('promotions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_promotions_restaurant_id'), table_name='promotions')
    op.alter_column('purchase_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_purchase_orders_restaurant_id'), table_name='purchase_orders')
    op.alter_column('qr_table_codes', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_qr_table_codes_restaurant_id'), table_name='qr_table_codes')
    op.alter_column('reservations', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_reservations_restaurant_id'), table_name='reservations')
    op.drop_index(op.f('ix_revenue_control_policies_restaurant_id'), table_name='revenue_control_policies')
    op.drop_index(op.f('ix_revenue_experiment_events_experiment_variant'), table_name='revenue_experiment_events')
    op.drop_index(op.f('ix_revenue_experiment_events_restaurant_recorded'), table_name='revenue_experiment_events')
    op.drop_index(op.f('ix_revenue_experiments_restaurant_status'), table_name='revenue_experiments')
    op.drop_index(op.f('ix_revenue_upsell_recommendations_restaurant_generated'), table_name='revenue_upsell_recommendations')
    op.drop_index(op.f('ix_service_autopilot_predictions_restaurant_target'), table_name='service_autopilot_predictions')
    op.drop_index(op.f('ix_service_autopilot_predictions_table_generated'), table_name='service_autopilot_predictions')
    op.alter_column('supplier_catalog_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_supplier_catalog_items_restaurant_id'), table_name='supplier_catalog_items')
    op.alter_column('table_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_table_orders_restaurant_id'), table_name='table_orders')
    op.alter_column('table_sessions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_table_sessions_restaurant_id'), table_name='table_sessions')
    op.alter_column('tables', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tables', 'table_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_tables_restaurant_id'), table_name='tables')
    op.alter_column('tva_reports', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tva_reports_restaurant_id'), table_name='tva_reports')
    op.alter_column('upsell_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_upsell_rules_restaurant_id'), table_name='upsell_rules')
    op.alter_column('vendors', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_vendors_restaurant_id'), table_name='vendors')
    op.alter_column('waitlist', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_waitlist_restaurant_id'), table_name='waitlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_waitlist_restaurant_id'), 'waitlist', ['restaurant_id'], unique=False)
    op.alter_column('waitlist', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_vendors_restaurant_id'), 'vendors', ['restaurant_id'], unique=False)
    op.alter_column('vendors', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_upsell_rules_restaurant_id'), 'upsell_rules', ['restaurant_id'], unique=False)
    op.alter_column('upsell_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tva_reports_restaurant_id'), 'tva_reports', ['restaurant_id'], unique=False)
    op.alter_column('tva_reports', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tables_restaurant_id'), 'tables', ['restaurant_id'], unique=False)
    op.alter_column('tables', 'table_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('tables', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_table_sessions_restaurant_id'), 'table_sessions', ['restaurant_id'], unique=False)
    op.alter_column('table_sessions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_table_orders_restaurant_id'), 'table_orders', ['restaurant_id'], unique=False)
    op.alter_column('table_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_supplier_catalog_items_restaurant_id'), 'supplier_catalog_items', ['restaurant_id'], unique=False)
    op.alter_column('supplier_catalog_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_service_autopilot_predictions_table_generated'), 'service_autopilot_predictions', ['table_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_service_autopilot_predictions_restaurant_target'), 'service_autopilot_predictions', ['restaurant_id', 'target_time'], unique=False)
    op.create_index(op.f('ix_revenue_upsell_recommendations_restaurant_generated'), 'revenue_upsell_recommendations', ['restaurant_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_revenue_experiments_restaurant_status'), 'revenue_experiments', ['restaurant_id', 'status'], unique=False)
    op.create_index(op.f('ix_revenue_experiment_events_restaurant_recorded'), 'revenue_experiment_events', ['restaurant_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_revenue_experiment_events_experiment_variant'), 'revenue_experiment_events', ['experiment_id', 'variant_key'], unique=False)
    op.create_index(op.f('ix_revenue_control_policies_restaurant_id'), 'revenue_control_policies', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_reservations_restaurant_id'), 'reservations', ['restaurant_id'], unique=False)
    op.alter_column('reservations', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_qr_table_codes_restaurant_id'), 'qr_table_codes', ['restaurant_id'], unique=False)
    op.alter_column('qr_table_codes', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_purchase_orders_restaurant_id'), 'purchase_orders', ['restaurant_id'], unique=False)
    op.alter_column('purchase_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_promotions_restaurant_id'), 'promotions', ['restaurant_id'], unique=False)
    op.alter_column('promotions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_payments_restaurant_id'), 'payments', ['restaurant_id'], unique=False)
    op.alter_column('payments', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.alter_column('orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_order_items_restaurant_id'), 'order_items', ['restaurant_id'], unique=False)
    op.alter_column('order_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_modifiers_restaurant_id'), 'menu_modifiers', ['restaurant_id'], unique=False)
    op.alter_column('menu_modifiers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_combos_restaurant_id'), 'menu_combos', ['restaurant_id'], unique=False)
    op.alter_column('menu_combos', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_categories_restaurant_id'), 'menu_categories', ['restaurant_id'], unique=False)
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_loyalty_accounts_restaurant_id'), 'loyalty_accounts', ['restaurant_id'], unique=False)
    op.alter_column('loyalty_accounts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_kds_station_configs_restaurant_id'), 'kds_station_configs', ['restaurant_id'], unique=False)
    op.alter_column('kds_station_configs', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_inventory_movements_restaurant_id'), 'inventory_movements', ['restaurant_id'], unique=False)
    op.alter_column('inventory_movements', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_inventory_items_restaurant_id'), 'inventory_items', ['restaurant_id'], unique=False)
    op.alter_column('inventory_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_guest_profiles_restaurant_id'), 'guest_profiles', ['restaurant_id'], unique=False)
    op.alter_column('guest_profiles', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_floor_sections_restaurant_id'), 'floor_sections', ['restaurant_id'], unique=False)
    op.alter_column('floor_sections', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cash_shifts_restaurant_id'), 'cash_shifts', ['restaurant_id'], unique=False)
    op.alter_column('cash_shifts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bills_restaurant_id'), 'bills', ['restaurant_id'], unique=False)
    op.alter_column('bills', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_auto_purchase_rules_restaurant_id'), 'auto_purchase_rules', ['restaurant_id'], unique=False)
    op.alter_column('auto_purchase_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_audit_events_source_module'), 'audit_events', ['source_module'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type_entity_id'), 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_owner'), 'alerts', ['owner'], unique=False)
    # ### end Alembic commands ###
